
package com.mycompany.aplicacionjava;

import com.theojansen.nfc.core.NfcDeviceException;
import com.theojansen.nfc.core.NfcServiceManager;
import com.theojansen.nfc.model.LightDirection;
import com.theojansen.nfc.model.MotorState;
import com.theojansen.nfc.model.RobotTelemetry;
import com.mycompany.aplicacionjava.ui.controller.TrackerUiController;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import java.awt.BorderLayout;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Random;

public class MainTrackerFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainTrackerFrame.class.getName());

    /**
     * Creates new form MainTrackerFrame
     */
    public MainTrackerFrame() {
        initComponents();
        setupCharts();                                  // ← ESTA LÍNEA FALTABA
        setExtendedState(javax.swing.JFrame.NORMAL);
        setSize(1100, 900);
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnToggleScan = new javax.swing.JButton();
        btnExportReport = new javax.swing.JButton();
        topMetricsPanel = new javax.swing.JPanel();
        servoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        barPitch = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        barYaw = new javax.swing.JProgressBar();
        motorPolarityPanel = new javax.swing.JPanel();
        lblMotorState = new javax.swing.JLabel();
        lblReversalsCount = new javax.swing.JLabel();
        powerPanel = new javax.swing.JPanel();
        Voltaje = new javax.swing.JLabel();
        lblVoltage = new javax.swing.JLabel();
        Bateria = new javax.swing.JLabel();
        barBattery = new javax.swing.JProgressBar();
        chartContainerPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        historyTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jToolBar1.setRollover(true);

        btnToggleScan.setText("Iniciar Escaneo");
        btnToggleScan.addActionListener(this::btnToggleScanActionPerformed);
        jToolBar1.add(btnToggleScan);

        btnExportReport.setText("Exportar Reporte (JSON)");
        btnExportReport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExportReport.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExportReport.addActionListener(this::btnExportReportActionPerformed);
        jToolBar1.add(btnExportReport);

        topMetricsPanel.setLayout(new java.awt.GridLayout(1, 3));

        servoPanel.setBackground(new java.awt.Color(255, 255, 255));
        servoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Servomotores"));
        servoPanel.setLayout(new java.awt.GridLayout(2, 2));

        jLabel1.setText("Pitch:");
        servoPanel.add(jLabel1);
        servoPanel.add(barPitch);

        jLabel2.setText("Yaw:");
        servoPanel.add(jLabel2);
        servoPanel.add(barYaw);

        topMetricsPanel.add(servoPanel);

        motorPolarityPanel.setBackground(new java.awt.Color(255, 255, 255));
        motorPolarityPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Polaridad del Motor"));
        motorPolarityPanel.setLayout(new java.awt.GridLayout(2, 2));

        lblMotorState.setText("Detenido");
        motorPolarityPanel.add(lblMotorState);

        lblReversalsCount.setText("Inversiones: 0");
        motorPolarityPanel.add(lblReversalsCount);

        topMetricsPanel.add(motorPolarityPanel);

        powerPanel.setBackground(new java.awt.Color(255, 255, 255));
        powerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Potencia"));
        powerPanel.setLayout(new java.awt.GridLayout(2, 2));

        Voltaje.setText("Voltaje");
        powerPanel.add(Voltaje);

        lblVoltage.setText("0.00 V");
        powerPanel.add(lblVoltage);

        Bateria.setText("Bateria");
        powerPanel.add(Bateria);
        powerPanel.add(barBattery);

        topMetricsPanel.add(powerPanel);

        chartContainerPanel.setBackground(new java.awt.Color(255, 255, 255));
        chartContainerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Sensores LDR (Norte / Sur / Este / Oeste)"));

        javax.swing.GroupLayout chartContainerPanelLayout = new javax.swing.GroupLayout(chartContainerPanel);
        chartContainerPanel.setLayout(chartContainerPanelLayout);
        chartContainerPanelLayout.setHorizontalGroup(
            chartContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        chartContainerPanelLayout.setVerticalGroup(
            chartContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Historial de Telemetria"));

        historyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Timestamp", "Voltaje (V)", "Bateria (%)", "Servo Pitch", "Servo Yaw", "LDR Dominante", "Sentido Motor"
            }
        ));
        jScrollPane1.setViewportView(historyTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(topMetricsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 938, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(chartContainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(topMetricsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chartContainerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnToggleScanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToggleScanActionPerformed
        if (!scanning) {
            startScanningProcess();
        } else {
            stopScanningProcess();
        }
    }//GEN-LAST:event_btnToggleScanActionPerformed

    private void btnExportReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportReportActionPerformed
      if (sessionHistory.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No hay registros para exportar.",
                "Exportacion vacia", JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setSelectedFile(new java.io.File("reporte.json"));
    int result = fileChooser.showSaveDialog(this);
    if (result != JFileChooser.APPROVE_OPTION) {
        return;
    }

    Gson gson = new GsonBuilder().setPrettyPrinting().create();
    try (FileWriter writer = new FileWriter(fileChooser.getSelectedFile())) {
        gson.toJson(sessionHistory, writer);
        JOptionPane.showMessageDialog(this, "Reporte exportado correctamente.");
    } catch (IOException e) {
        showDeviceError("No se pudo guardar el reporte: " + e.getMessage());
        }
    }//GEN-LAST:event_btnExportReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainTrackerFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bateria;
    private javax.swing.JLabel Voltaje;
    private javax.swing.JProgressBar barBattery;
    private javax.swing.JProgressBar barPitch;
    private javax.swing.JProgressBar barYaw;
    private javax.swing.JButton btnExportReport;
    private javax.swing.JButton btnToggleScan;
    private javax.swing.JPanel chartContainerPanel;
    private javax.swing.JTable historyTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblMotorState;
    private javax.swing.JLabel lblReversalsCount;
    private javax.swing.JLabel lblVoltage;
    private javax.swing.JPanel motorPolarityPanel;
    private javax.swing.JPanel powerPanel;
    private javax.swing.JPanel servoPanel;
    private javax.swing.JPanel topMetricsPanel;
    // End of variables declaration//GEN-END:variables
    // ------------------------------------------------------------------
    // Campos y logica agregados manualmente (fuera del area protegida)
    // ------------------------------------------------------------------

    private DefaultCategoryDataset ldrDataset;
    private boolean scanning = false;
    private final List<RobotTelemetry> sessionHistory = new ArrayList<>();
    private final SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");

    private NfcServiceManager nfcServiceManager;
    private TrackerUiController uiController;
    private Thread simulationThread;
    private volatile boolean simulationActive = false;

    public void initController(NfcServiceManager nfcServiceManager, TrackerUiController uiController) {
        this.nfcServiceManager = nfcServiceManager;
        this.uiController = uiController;
    }

    private void startScanningProcess() {
        if (nfcServiceManager == null) {
            nfcServiceManager = new NfcServiceManager();
        }
        if (uiController == null) {
            uiController = new TrackerUiController(this);
        }

        try {
            nfcServiceManager.initializeReader(null);
            nfcServiceManager.startContinuousScan(uiController);
            scanning = true;
            btnToggleScan.setText("Pausar Escaneo");
            JOptionPane.showMessageDialog(this,
                    "Lector NFC inicializado correctamente.\nEscaneando tags en segundo plano...",
                    "NFC Conectado", JOptionPane.INFORMATION_MESSAGE);
        } catch (NfcDeviceException ex) {
            int option = JOptionPane.showConfirmDialog(this,
                    ex.getMessage() + "\n\n¿Desea iniciar en MODO SIMULACIÓN para verificar la telemetría en el dashboard?",
                    "Lector NFC no detectado",
                    JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (option == JOptionPane.YES_OPTION) {
                startSimulation();
                scanning = true;
                btnToggleScan.setText("Pausar Escaneo (Simulación)");
            } else {
                scanning = false;
                btnToggleScan.setText("Iniciar Escaneo");
            }
        }
    }

    private void stopScanningProcess() {
        scanning = false;
        btnToggleScan.setText("Iniciar Escaneo");
        if (nfcServiceManager != null) {
            nfcServiceManager.stopContinuousScan();
        }
        stopSimulation();
    }

    private void startSimulation() {
        stopSimulation();
        simulationActive = true;
        simulationThread = new Thread(() -> {
            Random random = new Random();
            int reversals = 0;
            while (simulationActive) {
                int[] ldr = {
                        random.nextInt(256), // Norte
                        random.nextInt(256), // Sur
                        random.nextInt(256), // Oeste
                        random.nextInt(256)  // Este
                };
                int maxLdr = Math.max(Math.max(ldr[0], ldr[1]), Math.max(ldr[2], ldr[3]));
                LightDirection dir;
                if (maxLdr == ldr[0]) dir = LightDirection.NORTE;
                else if (maxLdr == ldr[1]) dir = LightDirection.SUR;
                else if (maxLdr == ldr[2]) dir = LightDirection.OESTE;
                else dir = LightDirection.ESTE;

                int pitch = 45 + random.nextInt(90);
                int yaw = random.nextInt(181);
                reversals += (random.nextInt(5) == 0 ? 1 : 0);
                MotorState mState = (reversals % 2 == 0) ? MotorState.ADELANTE : MotorState.ATRAS;
                double voltage = 4.80 + (random.nextDouble() * 0.45);
                int battery = 75 + random.nextInt(25);

                RobotTelemetry telemetry = new RobotTelemetry(
                        ldr,
                        (ldr[0] + ldr[1] + ldr[2] + ldr[3]) / 4.0,
                        dir,
                        pitch,
                        yaw,
                        reversals,
                        mState,
                        voltage,
                        battery,
                        System.currentTimeMillis(),
                        "SIM-TAG-4B82"
                );

                if (uiController != null) {
                    uiController.onTelemetryReceived(telemetry);
                }

                try {
                    Thread.sleep(1500);
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                    break;
                }
            }
        }, "SimulationNfcThread");
        simulationThread.setDaemon(true);
        simulationThread.start();
    }

    private void stopSimulation() {
        simulationActive = false;
        if (simulationThread != null && simulationThread.isAlive()) {
            simulationThread.interrupt();
        }
    }

    /**
     * Configura e incrusta el ChartPanel de JFreeChart dentro de
     * chartContainerPanel. Llamar una sola vez, después de initComponents().
     */
    private void setupCharts() {
        ldrDataset = new DefaultCategoryDataset();
        ldrDataset.addValue(0, "Intensidad", "Norte");
        ldrDataset.addValue(0, "Intensidad", "Sur");
        ldrDataset.addValue(0, "Intensidad", "Este");
        ldrDataset.addValue(0, "Intensidad", "Oeste");

        JFreeChart chart = ChartFactory.createBarChart(
                null, "Dirección", "Lectura LDR",
                ldrDataset, PlotOrientation.VERTICAL,
                false, true, false);

        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new java.awt.Dimension(600, 260));
        chartContainerPanel.setLayout(new BorderLayout());
        chartContainerPanel.add(chartPanel, BorderLayout.CENTER);
        chartContainerPanel.revalidate();
    }

    /**
     * Punto de entrada principal para refrescar todos los paneles
     * visuales al recibir una nueva lectura.
     */
    public void updateDashboard(RobotTelemetry telemetry) {
        if (telemetry == null) return;

        // 1. Gráfico de sensores LDR: [0: Norte, 1: Sur, 2: Oeste, 3: Este]
        int[] valores = telemetry.getLdrValues();
        if (valores != null && valores.length >= 4) {
            ldrDataset.setValue(valores[0], "Intensidad", "Norte");
            ldrDataset.setValue(valores[1], "Intensidad", "Sur");
            ldrDataset.setValue(valores[3], "Intensidad", "Este");
            ldrDataset.setValue(valores[2], "Intensidad", "Oeste");
        }

        // 2. Servomotores Pitch y Yaw
        barPitch.setValue(telemetry.getServoPitchAngle());
        barPitch.setString(telemetry.getServoPitchAngle() + "°");
        barYaw.setValue(telemetry.getServoYawAngle());
        barYaw.setString(telemetry.getServoYawAngle() + "°");

        // 3. Polaridad y tracción del motor
        lblMotorState.setText(telemetry.getMotorDirection().name());
        lblReversalsCount.setText("Inversiones: " + telemetry.getPolarityReversalsCount());

        // 4. Potencia y batería
        lblVoltage.setText(String.format(java.util.Locale.US, "%.2f V", telemetry.getOperatingVoltage()));
        barBattery.setValue(telemetry.getBatteryLevelPercent());
        barBattery.setString(telemetry.getBatteryLevelPercent() + "%");

        // 5. Historial en JTable
        DefaultTableModel model = (DefaultTableModel) historyTable.getModel();
        model.addRow(new Object[]{
                timeFormat.format(new Date(telemetry.getTimestamp())),
                String.format(java.util.Locale.US, "%.2f", telemetry.getOperatingVoltage()),
                telemetry.getBatteryLevelPercent() + "%",
                telemetry.getServoPitchAngle() + "°",
                telemetry.getServoYawAngle() + "°",
                telemetry.getPrimaryLightDirection() != null ? telemetry.getPrimaryLightDirection().name() : "N/A",
                telemetry.getMotorDirection().name()
        });

        sessionHistory.add(telemetry);
    }

    /** Muestra un error de dispositivo en un diálogo no bloqueante. */
    public void showDeviceError(String message) {
        JOptionPane.showMessageDialog(this, message, "Error de Dispositivo",
                JOptionPane.WARNING_MESSAGE);
    }
}
